jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        kvibes\SeleyaBundle\Entity\User:
            algorithm:        plaintext
            encode_as_base64: false
            iterations:       1
        IMAG\LdapBundle\User\LdapUser: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
                    superadmin: { password: superadminpass, roles: [ 'ROLE_SUPER_ADMIN' ] }
        ldap:
            id: imag_ldap.security.user.provider
        multiple:
            chain:
                providers: [ldap, in_memory]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/admin/login$
            security: false

        admin_area:
            pattern:    ^/admin
            provider: multiple
            imag_ldap:
                login_path:   /admin/login
            form_login:
                login_path: admin_login
                check_path: admin_login_check
                remember_me: true
            logout:
                path:   /admin/logout
                target: /admin
            remember_me:
                key:      "%secret%"
                lifetime: 31536000
                path:     /admin
                domain:   ~

        frontend:
            pattern:    ^/
            anonymous: true
            provider: ldap
            imag_ldap:
                login_path:   index
            form_login:
                login_path: index
                check_path: login_check
                remember_me: true
                use_referer: true
            logout:
                path:   /logout
                target: /
            remember_me:
                key:      "%secret%"
                lifetime: 31536000
                path:     /
                domain:   ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        

imag_ldap:
    client:
        host: %ldap_host%
        port: %ldap_port%
        version: %ldap_version%
#        username: admin # Optional
#        password: mmisv76dk # Optional
#        network_timeout: 10 # Optional
#        referrals_enabled: false
#        bind_username_before: true
        skip_roles: true

    user:
        base_dn: %ldap_user_basedn%
        name_attribute: uid
        attributes: [employeetype, cn]
#    role:
#        base_dn: dc=kvibes,dc=de
#        filter: (ou=group) #Optional
#        name_attribute: cn
#        user_attribute: member
#        user_id: username
